nohup ./a.out > log/client1 2>&1 &
nohup ./a.out > log/client2 2>&1 &
nohup ./a.out > log/client3 2>&1 &
nohup ./a.out > log/client4 2>&1 &
nohup ./a.out > log/client5 2>&1 &
nohup ./a.out > log/client6 2>&1 &
nohup ./a.out > log/client7 2>&1 &
nohup ./a.out > log/client8 2>&1 &
nohup ./a.out > log/client9 2>&1 &
nohup ./a.out > log/client10 2>&1 &
nohup ./a.out > log/client11 2>&1 &
nohup ./a.out > log/client12 2>&1 &
nohup ./a.out > log/client13 2>&1 &
nohup ./a.out > log/client14 2>&1 &
nohup ./a.out > log/client15 2>&1 &
nohup ./a.out > log/client16 2>&1 &
nohup ./a.out > log/client17 2>&1 &
nohup ./a.out > log/client18 2>&1 &
nohup ./a.out > log/client19 2>&1 &
nohup ./a.out > log/client20 2>&1 &
