# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/net_lib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/net_lib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/net_lib/CMakeFiles /root/net_lib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/net_lib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named net_lib

# Build rule for target.
net_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 net_lib
.PHONY : net_lib

# fast build rule for target.
net_lib/fast:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/build
.PHONY : net_lib/fast

src/connection_manager.o: src/connection_manager.cpp.o

.PHONY : src/connection_manager.o

# target to build an object file
src/connection_manager.cpp.o:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/connection_manager.cpp.o
.PHONY : src/connection_manager.cpp.o

src/connection_manager.i: src/connection_manager.cpp.i

.PHONY : src/connection_manager.i

# target to preprocess a source file
src/connection_manager.cpp.i:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/connection_manager.cpp.i
.PHONY : src/connection_manager.cpp.i

src/connection_manager.s: src/connection_manager.cpp.s

.PHONY : src/connection_manager.s

# target to generate assembly for a file
src/connection_manager.cpp.s:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/connection_manager.cpp.s
.PHONY : src/connection_manager.cpp.s

src/epoll_event_manager.o: src/epoll_event_manager.cpp.o

.PHONY : src/epoll_event_manager.o

# target to build an object file
src/epoll_event_manager.cpp.o:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/epoll_event_manager.cpp.o
.PHONY : src/epoll_event_manager.cpp.o

src/epoll_event_manager.i: src/epoll_event_manager.cpp.i

.PHONY : src/epoll_event_manager.i

# target to preprocess a source file
src/epoll_event_manager.cpp.i:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/epoll_event_manager.cpp.i
.PHONY : src/epoll_event_manager.cpp.i

src/epoll_event_manager.s: src/epoll_event_manager.cpp.s

.PHONY : src/epoll_event_manager.s

# target to generate assembly for a file
src/epoll_event_manager.cpp.s:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/epoll_event_manager.cpp.s
.PHONY : src/epoll_event_manager.cpp.s

src/io_event_pipe.o: src/io_event_pipe.cpp.o

.PHONY : src/io_event_pipe.o

# target to build an object file
src/io_event_pipe.cpp.o:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/io_event_pipe.cpp.o
.PHONY : src/io_event_pipe.cpp.o

src/io_event_pipe.i: src/io_event_pipe.cpp.i

.PHONY : src/io_event_pipe.i

# target to preprocess a source file
src/io_event_pipe.cpp.i:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/io_event_pipe.cpp.i
.PHONY : src/io_event_pipe.cpp.i

src/io_event_pipe.s: src/io_event_pipe.cpp.s

.PHONY : src/io_event_pipe.s

# target to generate assembly for a file
src/io_event_pipe.cpp.s:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/io_event_pipe.cpp.s
.PHONY : src/io_event_pipe.cpp.s

src/io_thread.o: src/io_thread.cpp.o

.PHONY : src/io_thread.o

# target to build an object file
src/io_thread.cpp.o:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/io_thread.cpp.o
.PHONY : src/io_thread.cpp.o

src/io_thread.i: src/io_thread.cpp.i

.PHONY : src/io_thread.i

# target to preprocess a source file
src/io_thread.cpp.i:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/io_thread.cpp.i
.PHONY : src/io_thread.cpp.i

src/io_thread.s: src/io_thread.cpp.s

.PHONY : src/io_thread.s

# target to generate assembly for a file
src/io_thread.cpp.s:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/io_thread.cpp.s
.PHONY : src/io_thread.cpp.s

src/listener.o: src/listener.cpp.o

.PHONY : src/listener.o

# target to build an object file
src/listener.cpp.o:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/listener.cpp.o
.PHONY : src/listener.cpp.o

src/listener.i: src/listener.cpp.i

.PHONY : src/listener.i

# target to preprocess a source file
src/listener.cpp.i:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/listener.cpp.i
.PHONY : src/listener.cpp.i

src/listener.s: src/listener.cpp.s

.PHONY : src/listener.s

# target to generate assembly for a file
src/listener.cpp.s:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/listener.cpp.s
.PHONY : src/listener.cpp.s

src/listener_thread.o: src/listener_thread.cpp.o

.PHONY : src/listener_thread.o

# target to build an object file
src/listener_thread.cpp.o:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/listener_thread.cpp.o
.PHONY : src/listener_thread.cpp.o

src/listener_thread.i: src/listener_thread.cpp.i

.PHONY : src/listener_thread.i

# target to preprocess a source file
src/listener_thread.cpp.i:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/listener_thread.cpp.i
.PHONY : src/listener_thread.cpp.i

src/listener_thread.s: src/listener_thread.cpp.s

.PHONY : src/listener_thread.s

# target to generate assembly for a file
src/listener_thread.cpp.s:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/listener_thread.cpp.s
.PHONY : src/listener_thread.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/net_manager.o: src/net_manager.cpp.o

.PHONY : src/net_manager.o

# target to build an object file
src/net_manager.cpp.o:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/net_manager.cpp.o
.PHONY : src/net_manager.cpp.o

src/net_manager.i: src/net_manager.cpp.i

.PHONY : src/net_manager.i

# target to preprocess a source file
src/net_manager.cpp.i:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/net_manager.cpp.i
.PHONY : src/net_manager.cpp.i

src/net_manager.s: src/net_manager.cpp.s

.PHONY : src/net_manager.s

# target to generate assembly for a file
src/net_manager.cpp.s:
	$(MAKE) -f CMakeFiles/net_lib.dir/build.make CMakeFiles/net_lib.dir/src/net_manager.cpp.s
.PHONY : src/net_manager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... net_lib"
	@echo "... src/connection_manager.o"
	@echo "... src/connection_manager.i"
	@echo "... src/connection_manager.s"
	@echo "... src/epoll_event_manager.o"
	@echo "... src/epoll_event_manager.i"
	@echo "... src/epoll_event_manager.s"
	@echo "... src/io_event_pipe.o"
	@echo "... src/io_event_pipe.i"
	@echo "... src/io_event_pipe.s"
	@echo "... src/io_thread.o"
	@echo "... src/io_thread.i"
	@echo "... src/io_thread.s"
	@echo "... src/listener.o"
	@echo "... src/listener.i"
	@echo "... src/listener.s"
	@echo "... src/listener_thread.o"
	@echo "... src/listener_thread.i"
	@echo "... src/listener_thread.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/net_manager.o"
	@echo "... src/net_manager.i"
	@echo "... src/net_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

